[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.48.1",
    "plotly>=5.0.0",
    "pandas>=1.3.0",
    "numpy>=1.21.0",
    "pydub>=0.25.0",
    "scipy>=1.7.0",
]
